<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Background.png" />
    <None Remove="Assets\Images\Cats\Cat_Dark.png" />
    <None Remove="Assets\Images\Dogs\Dog_Brown.png" />
    <None Remove="Assets\Images\Outlines\Cat_Outline_Grey.png" />
    <None Remove="Assets\Images\Outlines\Cat_Outline_Highlight.png" />
    <None Remove="Assets\Images\Outlines\Dog_Outline_Grey.png" />
    <None Remove="Assets\Images\Outlines\Dog_Outline_Highlight.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Images\Background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Cats\Cat_Dark.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Dogs\Dog_Brown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Outlines\Cat_Outline_Grey.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Outlines\Cat_Outline_Highlight.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Outlines\Dog_Outline_Grey.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\Outlines\Dog_Outline_Highlight.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\tamagotchi.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
